coverage:
  status:
    patch: off
    project:
      default:
        target: 100%
        threshold: 30%
      suspensive-react:
        target: 100%
        threshold: 30%
      suspensive-react-query:
        target: 100%
        threshold: 30%

comment:
  layout: "header, reach, flags, components"

component_management:
  individual_components:
    - component_id: suspensive-react
      name: "@suspensive/react"
      paths:
        - packages/react
    - component_id: suspensive-react-query
      name: "@suspensive/react-query"
      paths:
        - packages/react-query
