coverage:
  status:
    patch: off
    project:
      default:
        target: 100%
        threshold: 30%

comment:
  layout: 'header, reach, diff, flags, components'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

ignore:
  - '**/*.test-d.*'
  - '**/*.bench.*'

component_management:
  individual_components:
    - component_id: react
      name: '@suspensive/react'
      paths:
        - packages/react/**
    - component_id: react-query
      name: '@suspensive/react-query'
      paths:
        - packages/react-query/**
    - component_id: react-query
      name: '@suspensive/react-query-5'
      paths:
        - packages/react-query-5/**
    - component_id: react-await
      name: '@suspensive/react-await'
      paths:
        - packages/react-await/**
    - component_id: react-image
      name: '@suspensive/react-image'
      paths:
        - packages/react-image/**
