packages:
  - "configs/*"
  - "docs/*"
  - "examples/*"
  - "packages/*"

catalog:
  "babel-jest": "^29.7.0"
  "jest": "^29.7.0"
  # next
  "next": "^15.3.0"
  "@next/eslint-plugin-next": "^15.3.0"
  "@next/third-parties": "^15.3.0"
  "sharp": "^0.34.1"

  # tailwindcss
  "prettier-plugin-tailwindcss": "^0.6.11"
  "@tailwindcss/postcss": "^4.1.3"
  "tailwindcss": "^4.1.3"
  "clsx": "^2.1.1"

catalogs:
  react18:
    # react
    "react": "18.3.1"
    "@types/react": "18.3.12"
    # react-dom
    "react-dom": "18.3.1"
    "@types/react-dom": "18.3.1"

  react19:
    # react
    "react": "^19.1.0"
    "@types/react": "^19.1.0"
    # react-dom
    "react-dom": "^19.1.0"
    "@types/react-dom": "^19.1.2"
    # react-native
    "@react-navigation/native": "^7.0.14"
    "expo": "^52.0.24"
    "expo-router": "^4.0.16"
    "react-native": "^0.76.6"
    "react-native-web": "^0.19.13"
    "jest-expo": "^52.0.2"
    "@testing-library/react-native": "^12.9.0"

  # react-query
  react-query4:
    "@tanstack/react-query": "^4.36.1"
    "@tanstack/react-query-devtools": "^4.36.1"

  react-query5:
    "@tanstack/react-query": "^5.72.2"
    "@tanstack/react-query-devtools": "^5.72.2"
    "@tanstack/react-query-next-experimental": "^5.72.2"
