packages:
  - configs/*
  - docs/*
  - examples/*
  - packages/*

catalog:
  next: ^16.0.10
  '@next/eslint-plugin-next': ^16.0.10
  sharp: ^0.34.5
  '@tailwindcss/postcss': ^4.1.17
  tailwindcss: ^4.1.17
  clsx: ^2.1.1

catalogs:
  react18:
    react: 18.3.1
    '@types/react': 18.3.12
    react-dom: 18.3.1
    '@types/react-dom': 18.3.1
  react19:
    react: ^19.2.3
    '@types/react': ^19.2.7
    react-dom: ^19.2.3
    '@types/react-dom': ^19.2.3
  react-query4:
    '@tanstack/react-query': 4.42.0
  react-query5:
    '@tanstack/react-query': ^5.90.9
    '@tanstack/react-query-devtools': ^5.90.2

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - es5-ext
  - esbuild
  - msw
  - sharp

patchedDependencies:
  '@theguild/remark-mermaid': patches/@theguild__remark-mermaid.patch
