packages:
  - "configs/*"
  - "docs/*"
  - "examples/*"
  - "packages/*"

catalog:
  "expo": "^51.0.22"
  "expo-status-bar": "~1.12.1"
  "@expo/webpack-config": "^19.0.1"
  "babel-jest": "^29.7.0"
  "jest": "^29.7.0"
  "jest-expo": "^51.0.3"
  "@testing-library/react-native": "^12.5.2"

  # next
  "@next/eslint-plugin-next": "^14.2.14"
  "nextra": "^2.13.4"
  "next": "^14.2.14"
  "nextra-theme-docs": "^2.13.4"
  "sharp": "^0.33.5"

  # tailwindcss
  "autoprefixer": "^10.4.20"
  "postcss": "^8.4.47"
  "prettier-plugin-tailwindcss": "^0.6.6"
  "tailwindcss": "^3.4.10"
  "clsx": "^2.1.1"

  # codesandbox
  "@codesandbox/sandpack-react": "^2.19.1"
  "@codesandbox/sandpack-themes": "^2.0.21"
  "remark-sandpack": "^0.0.5"

  "axios": "^1.7.7"
  "zod": "^3.23.8"

catalogs:
  # react
  react18:
    "react": "^18.3.1"
    "react-dom": "^18.3.1"
    "@types/react": "^18.3.10"
    "@types/react-dom": "^18.3.0"
    "react-native": "^0.74.3"

  # react-query
  react-query4:
    "@tanstack/react-query": "^4.36.1"
    "@tanstack/react-query-devtools": "^4.36.1"

  react-query5:
    "@tanstack/react-query": "^5.59.0"
    "@tanstack/react-query-devtools": "^5.59.0"
    "@tanstack/react-query-next-experimental": "^5.59.0"
