packages:
  - configs/*
  - docs/*
  - examples/*
  - packages/*

catalog:
  babel-jest: ^29.7.0
  jest: ^29.7.0
  next: ^16.0.3
  '@next/eslint-plugin-next': ^16.0.3
  '@next/third-parties': ^16.0.3
  sharp: ^0.34.5
  '@tailwindcss/postcss': ^4.1.17
  tailwindcss: ^4.1.17
  clsx: ^2.1.1

catalogs:
  react18:
    react: 18.3.1
    '@types/react': 18.3.12
    react-dom: 18.3.1
    '@types/react-dom': 18.3.1
  react19:
    react: ^19.2.0
    '@types/react': ^19.2.5
    react-dom: ^19.2.0
    '@types/react-dom': ^19.2.3
    '@react-navigation/native': ^7.0.14
    expo: ^52.0.24
    expo-router: ^4.0.16
    react-native: ^0.76.6
    react-native-web: ^0.19.13
    jest-expo: ^52.0.2
    '@testing-library/react-native': ^12.9.0
  react-query4:
    '@tanstack/react-query': 4.42.0
    '@tanstack/react-query-devtools': 4.42.0
  react-query5:
    '@tanstack/react-query': ^5.90.9
    '@tanstack/react-query-devtools': ^5.90.2

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - es5-ext
  - esbuild
  - msw
  - sharp
