name: Feature Request
description: Suggest an idea
labels: [feature]
title: '[Feature]:'
body:
  - type: dropdown
    id: package
    attributes:
      label: Package Scope
      description: Is this issue related to a specific package?
      multiple: true
      options:
        - '@suspensive/react'
        - '@suspensive/react-dom'
        - '@suspensive/react-native'
        - '@suspensive/react-query'
        - '@suspensive/react-query-4'
        - '@suspensive/react-query-5'
        - '@suspensive/jotai'
        - '@suspensive/codemods'
        - etc
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      description: Description what feature you want
      label: Description
    validations:
      required: true

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: If you have suggestions on a fix for the bug
      placeholder: I think this is probably...
    validations:
      required: false

  - type: textarea
    id: etc
    attributes:
      label: etc.
    validations:
      required: false
